project:
  type: website
  output-dir: docs

website:
  title: "Will Zatkowski"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Projects
        menu:
          - href: text_analysis_project.qmd
            text: Text-Analysis Project
      

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



