project:
  type: website
  output-dir: docs

website:
  title: "Will Zatkowski"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Projects
        menu:
          - href: sql_project.qmd
            text: SQL Project
          - href: text_analysis_project.qmd
            text: Text-Analysis Project
          - href: r_package.qmd
            text: R Package
          - href: poster_project.qmd
            text: Poster Project
          - href: shinyapp_project.qmd
            text: Shiny App Project
      

format:
  html:
    theme:
      - darkly
      - brand
    css: styles.css
    toc: true



